version: "3.0"
services:
  golangserver:
    image: thteam47/golang-server:latest
    container_name: golangserver
    ports:
      - 9090:9090
    depends_on:
      - mongodb
      - elasticsearch
      - redis
    networks:
      - net11
  angular:
    image: thteam47/angular-fontend:latest
    container_name: angular
    ports:
      - 4200:80
    depends_on:
      - golangserver
    networks:
      - net11  
  elasticsearch:
    image: elasticsearch:7.14.0
    container_name: elasticsearch
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
    networks:
      - net11
    ports:
      - 9200:9200
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.13.4
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    networks:
      - net11
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
  mongodb:
    image: mongo:4.0.27-rc0
    container_name: mongodb
    ports:
      - 27017:27017
    networks:
      - net11
  redis:
    image: redis:6.0.3-alpine
    container_name: redis
    ports:
      - 6379:6379
    networks:
      - net11
networks:
  net11:
    driver: bridge
